[MODEL]
LOCAL_LLM_BASE_URL = "http://127.0.0.1:8080/v1"
LOCAL_LLM_MODEL     = "local-model"
LOCAL_LLM_API_KEY   = "not-needed"
LOCAL_LLM_TIMEOUT   = 120

[CONFIG.OFFICE]
CA_PATH = ""
PROXY = "http://localhost:9000"

[CONFIG.NOT_OFFICE]


# MCP Servers List
[mcpServers.knowledge]
url = "http://localhost:8001/mcp"
auth = "None"

[mcpServers.weather]
command = "uv"
args = [
    "run",
    "./server/stdio_weather_server.py"
]
env = {}
    