[MODEL]
LOCAL_MODEL_BASE_URL = "http://127.0.0.1:8000/v1"
LOCAL_LLM_MODEL     = "local-model"
LOCAL_LLM_API_KEY   = "not-needed"
LOCAL_LLM_TIMEOUT   = 120

[mcpServers.clean_http]
url = "http://localhost:8000/mcp"
#auth = "None"
[mcpServers.clean_sse]
url = "http://localhost:8001/mcp"
auth = "None"

    